.PHONY: all test1 test2

all: test1 test2

test1:
	@echo
	@echo "##### TESTING test1"
	@more test1.tr
	@echo
	@../src/trantor test1.tr

test2:
	@echo
	@echo "##### TESTING test2"
	@../src/trantor test2.tr

